echobyte/customer/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signin/', views.signin, name= "signin"),
    path('signup/', views.signup, name= "signup"),
    path('signout/', views.signout, name= "signout"),
    path('otp_verification/<pk>/', views.otp_verification, name= "otp_verification"),
    path('profile/', views.profile, name= "profile"),
    path('edit_profile/', views.edit_profile, name= "edit_profile"),
    path('address/', views.address, name= "address"),
    path('add_address/', views.add_address, name= "add_address"),
    path('edit_address/<pk>', views.edit_address, name= "edit_address"),
    path('delete_address/<pk>', views.delete_address, name= "delete_address"),
    path('change_password/', views.change_password, name= "change_password"),
    path('forgot_password',views.forgot_password, name="forgot_password"),
    path('otp_verification_forgot_password/<pk>/', views.otp_verification_forgot_password, name= "otp_verification_forgot_password"),
    path('reset_password/<pk>',views.reset_password, name="reset_password"),
    path('wallet/', views.wallet, name= "wallet"),  
]

echobyte/echobyte/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_admin.urls')),
    path('',include('user_home.urls')),
    path('',include('customer.urls')),
    path('',include('product.urls')),
    path('',include('category.urls')),
    path('',include('order.urls')),
    path('',include('coupon.urls')),
    path('',include('banner.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

echobyte/order/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('cart/', views.cart, name= "cart"),
    path('add_to_cart/', views.add_to_cart, name= "add_to_cart"),
    path('detele_cart_item/<pk>/', views.delete_cart_item, name= "delete_cart_item"),
    path('add_cart_item_quantity/<pk>/', views.add_cart_item_quantity, name= "add_cart_item_quantity"),
    path('sub_cart_item_quantity/<pk>/', views.sub_cart_item_quantity, name= "sub_cart_item_quantity"),
    path('checkout/', views.checkout, name= "checkout"),
    path('order_success/', views.order_success, name= "order_success"),
    path('list_orders/', views.list_orders, name= "list_orders"),
    path('change_order_status/<pk>/', views.change_order_status, name= "change_order_status"),
    path('my_orders/', views.my_orders, name= "my_orders"),
    path('order_details/<pk>/', views.order_details, name= "order_details"),
    path('cancel_order/<pk>/', views.cancel_order, name= "cancel_order"),
    path('delivery_list/', views.delivery_list, name= "delivery_list"),
    path('return_order/<pk>/', views.return_order, name= "return_order"),
    path('return_list/', views.return_list, name= "return_list"),
    path('change_return_status/<pk>/', views.change_return_status, name= "change_return_status"),
    path('add_to_wishlist/', views.add_to_wishlist, name= "add_to_wishlist"),
    path('wishlist/', views.wishlist, name= "wishlist"),
    path('remove_from_wishlist/<pk>/', views.remove_from_wishlist, name= "remove_from_wishlist"),
    path('payment_failure/', views.payment_failure, name= "payment_failure"),
    path('download_invoice/<pk>/', views.download_invoice, name= "download_invoice"),
    path('make_payment/<int:pk>/', views.make_payment, name='make_payment'),
    path('make_payment_failure/<int:pk>/', views.make_payment_failure, name='make_payment_failure'),
    
    ]

echobyte/customer/models.py
from django.db import models
from django.contrib.auth.models import User

class Customer(models.Model):
    LIVE = 1
    DELETE = 0
    DELETE_CHOICES = ((LIVE, 'Live'), (DELETE, 'Delete'))
    name = models.CharField(max_length=50, null = True)
    phone = models.CharField(max_length=50, unique=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    delete_status = models.IntegerField(choices=DELETE_CHOICES, default=LIVE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    otp = models.IntegerField(null = True, blank = True)
    is_verified = models.BooleanField(default = False)
    def __str__(self):
        return self.name
    

class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='addresses', null = True)  # Added related_name
    name = models.CharField(max_length=50)
    phone = models.CharField(max_length=50)
    address = models.TextField()
    pincode = models.PositiveIntegerField()
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    def __str__(self):
        return self.user.username+ "'s address"
class Wallet(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    balance = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    last_updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=20, choices=[('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='active')

    def __str__(self):
        return f"{self.user.customer.name}'s Wallet"

    
    

echobyte/order/models.py
from django.db import models
from django.contrib.auth.models import User
from product.models import Product, ProductVariant
from customer.models import Address

# Create your models here.
class Cart(models.Model):
    owner = models.OneToOneField(User,on_delete=models.CASCADE)
    
class CartItems(models.Model):
    product = models.ForeignKey(ProductVariant, on_delete=models.CASCADE, related_name = 'added_products')
    quantity = models.PositiveIntegerField(default = 1)
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE, related_name = 'added_cart_items')
    created_at = models.DateTimeField(auto_now_add=True, null = True)
    
class Order(models.Model):
    ORDER_CONFIRMED = 1
    ORDER_SHIPPED = 2
    ORDER_DELIVERED = 3
    ORDER_CANCELLED = -1
    ORDER_STATUS_CHOICES = (
        (ORDER_CONFIRMED, 'ORDER_CONFIRMED'),
        (ORDER_SHIPPED, 'ORDER_SHIPPED'),
        (ORDER_DELIVERED, 'ORDER_DELIVERED'),
        (ORDER_CANCELLED, 'ORDER_CANCELLED')
    )

    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.SET_NULL, null=True, blank=True)
    products = models.ManyToManyField(ProductVariant, through='OrderItem')
    amount =  models.DecimalField( max_digits=10, decimal_places=2)
    discount_amount = models.DecimalField(max_digits=10, decimal_places=2, null = True, blank = True)
    payment_method = models.CharField(max_length=50)
    razor_pay_id = models.CharField(max_length=50, null = True, blank =True)
    is_paid = models.BooleanField(default = False,null = True, blank =True)
    order_status = models.IntegerField(choices=ORDER_STATUS_CHOICES, default=ORDER_CONFIRMED)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True)

class OrderItem(models.Model):
    ORDER_CONFIRMED = 1
    ORDER_SHIPPED = 2
    ORDER_DELIVERED = 3
    ORDER_RETURN_REQUESTED = 4
    ORDER_RETURNED = 5
    ORDER_CANCELLED = -1
    ORDER_CANCELLED_BY_SELLER = -2

    ORDER_STATUS_CHOICES = (
        (ORDER_CONFIRMED, 'Confirmed'),
        (ORDER_SHIPPED, 'Shipped'),
        (ORDER_DELIVERED, 'Delivered'),
        (ORDER_CANCELLED, 'Cancelled'),
        (ORDER_CANCELLED_BY_SELLER, 'Cancelled by Seller'),
        (ORDER_RETURN_REQUESTED, 'Return Requested'),
        (ORDER_RETURNED, 'Returned')
    )

    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='order_items')
    product = models.ForeignKey(ProductVariant, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    total_amount = amount = models.DecimalField(max_digits=10, decimal_places=2, null = True, blank = True)
    discount_amount = models.DecimalField(max_digits=10, decimal_places=2, null = True, blank = True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    payment_method = models.CharField(max_length=50,null = True, blank =True)
    razor_pay_id = models.CharField(max_length=50, null = True, blank =True)
    order_status = models.IntegerField(choices=ORDER_STATUS_CHOICES, default=ORDER_CONFIRMED)
    address = models.ForeignKey(Address, on_delete=models.SET_NULL, null=True, blank=True)
    is_paid = models.BooleanField(default = False,null = True, blank =True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True)

class ReturnOrder(models.Model):
    RETURN_REQUESTED = 1
    RETURNED = 2
    STATUS_CHOICES = ((RETURN_REQUESTED, 'Return Requested'),
        (RETURNED,'Returned'))
    user = models.ForeignKey(User,on_delete=models.SET_NULL, null = True, blank = True)
    product = models.ForeignKey(ProductVariant,on_delete=models.SET_NULL, blank = True, null = True)
    order = models.ForeignKey(OrderItem,on_delete=models.SET_NULL, null = True)
    address = models.ForeignKey(Address, on_delete=models.SET_NULL, null=True)
    reason = models.TextField()
    amount_to_refund = models.DecimalField( max_digits=10, decimal_places=2)
    return_status = models.IntegerField(choices=STATUS_CHOICES, default=RETURN_REQUESTED)
    created_at = models.DateTimeField(auto_now_add=True)
class Wishlist(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    product = models.ForeignKey(ProductVariant,on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
     



     
     

    
     



         
     
     
    
    


    

echobyte/customer/templates/add-address.html
{% extends 'base.html' %}
{% load static %}
{% block title%}Address {% endblock %}
{% block content %}


        <!--====== App Content ======-->
        <div class="app-content">

         

            <!--====== Section 2 ======-->
            <div class="u-s-p-b-60">

                <!--====== Section Content ======-->
                <div class="section__content">
                    <div class="dash">
                        <div class="container">
                            <div class="row">
                                <div class="col-lg-3 col-md-12">

                                    <!--====== Dashboard Features ======-->
                                   {% include 'profile-side-bar.html' %}
                                    <!--====== End - Dashboard Features ======-->
                                </div>
                                <div class="col-lg-9 col-md-12">
                                    <div class="dash__box dash__box--shadow dash__box--radius dash__box--bg-white">
                                        <div class="dash__pad-2">
                                            <h1 class="dash__h1 u-s-m-b-14">Add new Address</h1>

                                            <span class="dash__text u-s-m-b-30">We need an address where we could deliver products.</span>
                                            <form class="dash-address-manipulation" method="post" action="{% url "add_address" %}">
                                                {% csrf_token %}
                                                <div class="gl-inline">
                                                    <div class="u-s-m-b-30">

                                                        <label class="gl-label" for="address-fname">NAME *</label>

                                                        <input name="name" class="input-text input-text--primary-style" type="text" id="address-fname" placeholder="Name"></div>
                                                  
                                                </div>
                                                <div class="gl-inline">
                                                    <div class="u-s-m-b-30">

                                                        <label   class="gl-label" for="address-phone"> PHONE *</label>

                                                        <input  name="phone" class="input-text input-text--primary-style" type="text" id="address-phone" placeholder="Phone Number"></div>
                                                    <div class="u-s-m-b-30">

                                                        <label class="gl-label" for="address-street">ADDRESS *</label>

                                                        <input  name="address" class="input-text input-text--primary-style" type="text" id="address-street" placeholder="House Name and Street"></div>
                                                </div>
                                                <div class="gl-inline">
                                                    
                                                    <div class="u-s-m-b-30">

                                                        <!--====== Select Box ======-->

                                                        <label class="gl-label" for="address-state">STATE/PROVINCE *</label>
                                                        <select name="state" class="select-box select-box--primary-style" id="address-state">
                                                            <option selected value="">Choose State/Province</option>
                                                            <option value="Kerala">Kerala</option>
                                                            <option value="Tamil Nadu">Tamil Nadu</option>
                                                            <option value="Karnataka">Karnataka</option>
                                                         
                                                            
                                                        </select>
                                                        <!--====== End - Select Box ======-->
                                                    </div>
                                                </div>
                                                <div class="gl-inline">
                                                    <div class="u-s-m-b-30">

                                                        <label class="gl-label" for="address-city">TOWN/CITY *</label>

                                                        <input name="town" placeholder="Town/City Name" class="input-text input-text--primary-style" type="text" id="address-city"></div>
                                                    <div class="u-s-m-b-30">

                                                        <label class="gl-label" for="address-street">ZIP/POSTAL CODE *</label>

                                                        <input name="pincode" class="input-text input-text--primary-style" type="text" id="address-postal" placeholder="Zip/Postal Code"></div>
                                                </div>
                                                <input type="hidden" name="source" value="{{ request.GET.source }}">

                                                <button class="btn btn--e-brand-b-2" type="submit">SAVE</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--====== End - Section Content ======-->
            </div>
            <!--====== End - Section 2 ======-->
        </div>
        <!--====== End - App Content ======-->
        {% endblock %}

echobyte/customer/templates/address.html
{% extends 'base.html' %}
{% load static %}
{% block title%}Address {% endblock %}
{% block content %}


        <!--====== App Content ======-->
        <div class="app-content">



            <!--====== Section 2 ======-->
            <div class="u-s-p-b-60">

                <!--====== Section Content ======-->
                <div class="section__content">
                    <div class="dash">
                        <div class="container">
                            <div class="row">
                                <div class="col-lg-3 col-md-12">

                                   {% include "profile-side-bar.html" %}
                                    <!--====== End - Dashboard Features ======-->
                                </div>
                                <div class="col-lg-9 col-md-12">
                                    <div class="dash__box dash__box--shadow dash__box--radius dash__box--bg-white u-s-m-b-30">
                                        <div class="dash__pad-2">
                                            <div class="dash__address-header">
                                                <h1 class="dash__h1">Address Book</h1>
                                                
                                            </div>
                                        </div>
                                    </div>
                                    <div class="dash__box dash__box--shadow dash__box--bg-white dash__box--radius u-s-m-b-30">
                                        <div class="dash__table-2-wrap gl-scroll">
                                            <table class="dash__table-2">
                                                <thead>
                                                    <tr>
                                                        <th>Full Name</th>
                                                        <th>Address</th>
                                                        <th>Region</th>
                                                        <th>Phone Number</th>
                                                        <th>Action</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    {% for address in address %}
                                                    <tr>
                                                        
                                                        <td>{{address.name}}</td>
                                                        <td>{{address.address}}
                                                        </td>
                                                        <td>{{address.state}}</td>
                                                        <td>{{address.phone}}</td>
                                                        <td><a class="address-book-edit btn--e-transparent-platinum-b-2" href="{% url 'edit_address' address.pk %}">Edit</a>  <a href="{% url 'delete_address' address.pk %}"><button class="btn btn-danger">Delete</button></td></a> 
                                                    </tr>
                                                    {% endfor %}
                                                    
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                    <div>

                                        <a class="dash__custom-link btn--e-brand-b-2" href="{% url 'add_address' %}"><i class="fas fa-plus u-s-m-r-8"></i>

                                            <span>Add New Address</span></a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--====== End - Section Content ======-->
            </div>
            <!--====== End - Section 2 ======-->
        </div>
        <!--====== End - App Content ======-->

{% endblock %}

echobyte/customer/templates/change_password.html
{% extends 'base.html' %}
{% load static %}
{% block title%}Change Password  {% endblock %}
{% block content %}


        <!--====== App Content ======-->
        <div class="app-content">

         

            <!--====== Section 2 ======-->
            <div class="u-s-p-b-60">

                <!--====== Section Content ======-->
                <div class="section__content">
                    <div class="dash">
                        <div class="container">
                            <div class="row">
                                <div class="col-lg-3 col-md-12">

                                    <!--====== Dashboard Features ======-->
                                   {% include 'profile-side-bar.html' %}
                                    <!--====== End - Dashboard Features ======-->
                                </div>
                                <div class="col-lg-9 col-md-12">
                                    <div class="dash__box dash__box--shadow dash__box--radius dash__box--bg-white">
                                        <div class="dash__pad-2">
                                            <h1 class="dash__h1 u-s-m-b-14">Change Password</h1>
                                            <form class="dash-address-manipulation" method="post" action="">
                                                {% csrf_token %}
                                                <div class="gl-inline">
                                                    <div class="u-s-m-b-30">

                                                        <label class="gl-label" for="address-fname">Current Password *</label>

                                                        <input name="current_password" class="input-text input-text--primary-style" type="text" id="" placeholder="Enter Current Password" required></div>
                                                  
                                                </div>
                                                <div class="gl-inline">
                                                    <div class="u-s-m-b-30">

                                                        <label   class="gl-label" for="address-phone"> New Password *</label>

                                                        <input  name="new_password_1"  class="input-text input-text--primary-style" type="password"  placeholder="Enter New Password" required></div>
                                                    <div class="u-s-m-b-30">

                                                        <label class="gl-label" for="address-street">Confirm Password *</label>

                                                        <input  name="new_password_2" value="" class="input-text input-text--primary-style" type="password" id="address-street" placeholder="Re-enter Password" required></div>
                                                </div>

                                                <div>
                                                    {% if error_message %}
                                                    <p class="text-danger">{{error_message}}</p>
                                                    {% endif %}

                                                    {% if success_message %}
                                                    <p class="text-success">{{success_message}}</p>
                                                    {% endif %}
                                                </div>
                                                <button class="btn btn--e-brand-b-2" type="submit">SAVE</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--====== End - Section Content ======-->
            </div>
            <!--====== End - Section 2 ======-->
        </div>
        <!--====== End - App Content ======-->
        {% endblock %}

echobyte/customer/templates/my-order.html
{% extends 'base.html' %}
{% load static %}
{% block title%}Orders {% endblock %}
{% block content %}


        <!--====== App Content ======-->
        <div class="app-content">

            <!--====== Section 1 ======-->
            <div class="u-s-p-y-60">

                <!--====== Section Content ======-->
                <div class="section__content">
                    <div class="container">
                        <div class="breadcrumb">
                            <div class="breadcrumb__wrap">
                                <ul class="breadcrumb__list">
                                    <li class="has-separator">

                                        <a href="index.html">Home</a></li>
                                    <li class="is-marked">

                                        <a href="dash-my-order.html">My Account</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--====== End - Section 1 ======-->


            <!--====== Section 2 ======-->
            <div class="u-s-p-b-60">

                <!--====== Section Content ======-->
                <div class="section__content">
                    <div class="dash">
                        <div class="container">
                            <div class="row">
                                <div class="col-lg-3 col-md-12">

                                    <!--====== Dashboard Features ======-->
                                   {% include "profile-side-bar.html" %}
                                   
                                    <!--====== End - Dashboard Features ======-->
                                </div>
                                <div class="col-lg-9 col-md-12">
                                    <div class="dash__box dash__box--shadow dash__box--radius dash__box--bg-white u-s-m-b-30">
                                        <div class="dash__pad-2">
                                            <h1 class="dash__h1 u-s-m-b-14">My Orders</h1>

                                            <span class="dash__text u-s-m-b-30">Here you can see all products that have been delivered.</span>
                                            <form class="m-order u-s-m-b-30">
                                                <div class="m-order__select-wrapper">

                                                    <label class="u-s-m-r-8" for="my-order-sort">Show:</label><select class="select-box select-box--primary-style" id="my-order-sort">
                                                        <option selected>Last 5 orders</option>
                                                        <option>Last 15 days</option>
                                                        <option>Last 30 days</option>
                                                        <option>Last 6 months</option>
                                                        <option>Orders placed in 2018</option>
                                                        <option>All Orders</option>
                                                    </select></div>
                                            </form>
                                            <div class="m-order__list">
                                                {% for order in orders %}
                                                <div class="m-order__get">
                                                    <div class="manage-o__header u-s-m-b-30">
                                                        <div class="dash-l-r">
                                                            <div>
                                                                <div class="manage-o__text-2 u-c-secondary">Order #305423126</div>
                                                                <div class="manage-o__text u-c-silver">Placed on {{ order.created_at }}</div>
                                                            </div>
                                                            <div>
                                                                <div class="dash__link dash__link--brand">

                                                                    <a href="dash-manage-order.html">MANAGE</a></div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="manage-o__description">
                                                        <div class="description__container">
                                                            <div class="description__img-wrap">

                                                                <img class="u-img-fluid" src="{{ order.product.product.images.first.image.url }}" alt=""></div>
                                                            <div class="description-title">{{order.product.product.brand}} {{order.product.product.title}} ({{order.product.variant_name}})</div>
                                                        </div>
                                                        <div class="description__info-wrap">
                                                            <div>
                                                                <div class="manage-o__badge badge--processing">{{ order.get_order_status_display }}</div>

                                                                
                                                            <div>

                                                                <span class="manage-o__text-2 u-c-silver">Quantity:

                                                                    <span class="manage-o__text-2 u-c-secondary">{{order.quantity}}</span></span></div>
                                                            <div>

                                                                <span class="manage-o__text-2 u-c-silver">Total:

                                                                    <span class="manage-o__text-2 u-c-secondary">{{order.amount}}</span></span></div>
                                                        </div>
                                                    </div>
                                                </div>
                                                </div>
                                                {% endfor %}
                                                
                                                
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--====== End - Section Content ======-->
            </div>
            <!--====== End - Section 2 ======-->
        </div>
        <!--====== End - App Content ======-->


       {% endblock %}